apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
data:
  BABEL_DEFAULT_LOCALE: fr_FR
  HABITICA_USER_ID: 4d2d5719-ee22-45bf-9feb-5413cdc5764b
