apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-aws-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: {{ .Values.appName }}-aws-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: {{ .Values.awsSecretsKey }}
      property: POSTGRES_PASSWORD
  - secretKey: OPEN_WEATHER_API_KEY
    remoteRef:
      key: {{ .Values.awsSecretsKey }}
      property: OPEN_WEATHER_API_KEY
  - secretKey: HABITICA_API_TOKEN
    remoteRef:
      key: {{ .Values.awsSecretsKey }}
      property: HABITICA_API_TOKEN
