apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyboard-listener
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: keyboard-detector
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Detecting keyboard id..."
              KEYBOARD_PATH=$(ls /input-devices | grep -- '-kbd$' | head -n 1)
              if [ -n "$KEYBOARD_PATH" ]; then
                echo "/dev/input/by-id/$KEYBOARD_PATH" > /config/keyboard_path
                echo "Keyboard device set to: /dev/input/by-id/$KEYBOARD_PATH"
              else
                echo "" > /config/keyboard_path
                echo "No keyboard detected"
              fi
          volumeMounts:
            - name: inputs-by-id
              mountPath: /dev/input/by-id
            - name: keyboard-config
              mountPath: /config

      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.env.IMAGE_TAG }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "scripts/listen-for-print"]
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: keyboard
              mountPath: /dev/usb/hiddev0
            - name: keyboard-config
              mountPath: /config
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deploymentEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: inputs-by-id
          hostPath:
            path: /dev/input/by-id
            type: Directory
        - name: keyboard-config
          emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
