apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Values.appName }}-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.appName }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-aws-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}-postgres-pvc
