"""empty message

Revision ID: 682e9c60ca45
Revises: baa73395892b
Create Date: 2025-02-04 21:42:06.068226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682e9c60ca45'
down_revision = 'baa73395892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_printable', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.drop_column('is_printable')

    # ### end Alembic commands ###
