"""empty message

Revision ID: baa73395892b
Revises: 
Create Date: 2025-02-02 17:23:46.674090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa73395892b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('errors', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.drop_column('errors')

    # ### end Alembic commands ###
