"""empty message

Revision ID: be1a9d096657
Revises: 
Create Date: 2025-03-23 15:51:53.437088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be1a9d096657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('function', sa.String(), nullable=False),
    sa.Column('call_args_kwargs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'SENT', native_enum=False), nullable=False),
    sa.Column('print_data', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('is_printable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_job')
    op.drop_table('cached_call')
    # ### end Alembic commands ###
