name: Deploy to argocd

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}-deploy-main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: arn:aws:iam::810574566145:role/GHActionsECRRole

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag and push image to ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: daily-planner
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
      outputs:
        image_tag: $IMAGE_TAG

    - name: Update image tag in Helm values
      run: |
        sed -i "s|IMAGE_TAG:.*|IMAGE_TAG: '${{ steps.build-image.outputs.image_tag }}'|" helm/values.yaml
        git config --global user.email "${{ vars.GITHUB_ACTOR_ID }}@users.noreply.github.com"
        git config --global user.name "${{ vars.GITHUB_ACTOR }}"
        git add helm/values.yaml
        git commit -m "Update image tag to ${{ steps.build-image.outputs.image_tag }}"
        git push
